apiVersion: v1
kind: Service
metadata:
  name: wishlists
  labels:
    app: wishlists
spec:
  selector:
    app: wishlists
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080